on:
   push:
      branches:
        -main

permissions:
  contents: write

jobs:
  hello-world:
     runs-on: ubuntu-latest
     setps:
       - name: run
         run: echo "Hello wolrd"