
name: Hello World

on:
   workflow_dispatch:
     inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

   
   push:
     branches:
        - main


jobs:
  hello-world:
     runs-on: ubuntu-latest
     steps:
     
      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "jq: $(jq --version)" 
          echo "curl: $(curl --version)" 

      - name: Show System Information
        run: |
          uname -a
          echo "Current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Archetecture: $RUNNER_ARCH"

      - name: Run a one-line script
        run: echo "Hello wolrd $(whoami)" ${{ inputs.username }}

      - name: Show Current Date Information
        run: date
  
  checkout-example:
     runs-on: ubuntu-latest

     steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display files in the repository
        run: ls -la
