
name: Hello World

on:
   workflow_dispatch:
   
   push:
     branches:
        - main


jobs:
  hello-world:
     runs-on: ubuntu-latest
     steps:
     
      - name: Show System Information
        run: |
          uname -a
          echo "Current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Archetecture: $RUNNER_ARCH"

      - name: Run a one-line script
        run: echo "Hello wolrd"

      - name: Show Current Date Information
        run: date